### ISSUE TITLE
Mockup ideas for Webmaker "teach" landing page

### ISSUE THREAD

**Issue by keyboardkat** [MozillaHive/ARCHIVEhivelabs#11]
To do: Consider and mock-up some ideas for a landing page that can either go on https://webmaker.org/teach or elsewhere which features our "best in show" top kits (currently, Mobile Design Kit, Hack Your Notebook, LoFi NoFi Kit, etc) on Webmaker site. Inspired by Made in Code landing page.

Will sketch out some ideas today, and make a few design mock-ups for this late this week/early next week.

**Comment by chrislarry33** [comment]
I add Cogdog's new one as well: https://cogdog.makes.org/thimble/OTM3NDI2OTQ0/imageseeking-for-fantastic-visual-metaphors

Looking forward to seeing.

**Comment by keyboardkat** [comment]
Thanks @chrislarry33 , great addition. Also really liking the look of Made With Code's resources section (great icons/layout). Will keep this in mind too; sketching first thoughts on Monday. https://www.madewithcode.com/resources

**Comment by keyboardkat** [comment]
Sketches: <img src="http://s21.postimg.org/vfwtu3r9j/Teach_Page_V1.jpg"> (Thinking about whether between action-based tiles best, or kits pulled directly from MakeAPI)

**Comment by keyboardkat** [comment]
And mockup #1: (version with kits pulled directly form MakeAPI)
<img src="http://s21.postimg.org/y7g3kpps7/Kit_Screenshot1.jpg">

**Comment by keyboardkat** [comment]
I also suggest we redirect https://webmaker.org/teach-templates (linked to from main /Explore page, currently goes to a 404 link) AND https://webmaker.org/teach 

to 

https://webmaker.org/make-your-own 

so that make-your-own is the canonical place for _both_ teaching kit templates, and 4 "best of show" kits.

**Comment by keyboardkat** [comment]
Quick update that this has informed dev team's updating of the above pages and is now in production at https://bugzilla.mozilla.org/show_bug.cgi?id=1030883

:) yay!

**Comment by chrislarry33** [comment]
awsm nice
