### ISSUE TITLE
Gather data from Hive Labs survey + interview

### ISSUE THREAD

**Issue by keyboardkat** [MozillaHive/ARCHIVEhivelabs#13]
To do: Gather statistically significant (and reportable) data from Hive Labs survey and interviews to start summarizing our key findings.

**Comment by keyboardkat** [comment]
Have been able to gather some interesting initial findings from 21 respondents to Hive Survey [Note: At this point I'm only drawing out _significant_ data, i.e. not the numbers that are less strong].
- <strong>Locations that have responded:</strong> 
  Vancouver, Indonesia, Chattanooga, Cha, Hive Bay Area, Toronto, NYC, Surabaya, Chicago, Bay Area, Pittsburgh
- <strong>Respondents MORE likely to use a prototype tool that:</strong>
  1) Provides them with help/collaboration from other Hive members. 
  2) Provides them with a way to track ideas, and see progress. 
  3) Provides them with an overview of tools to use for the task. 
- <strong>LESS likely to use a prototype tool that: </strong>
  1) Provides them with suggestions on how to _get started_ building their ideas. 
  2) Provides them with design suggestions or review. 

<img src="http://s28.postimg.org/lakfmkefx/Screen_Shot_2014_07_02_at_3_43_16_PM.png">
- <strong>Methods OFTEN used to brainstorm ideas right now: </strong>
  1) Writing them out on paper - notebooks, whiteboards, etc. 
  2) Talking them out in a group - G+, Hangouts, etc. 
- <strong>LESS used methods to brainstorm ideas: </strong>
  1) Writing them out online. 
  2) Recording/taking photos online. 

<img src="http://s28.postimg.org/5ax6p9t0d/Screen_Shot_2014_07_02_at_3_51_20_PM.png">
- <strong>MOST successful way for Hives to collaborate: </strong>
  1) In-person meetings. 
  2) Ideation charettes/codesign sessions/workshops. 
  3) Ambient gatherings/networking events, hangouts. 
- <strong>LEAST successful ways for Hives to collaborate: </strong>
  1) Virtual meetings. 
  2) Virtual discussions, listserves.

<img src="http://s28.postimg.org/5qd1w14bh/Screen_Shot_2014_07_02_at_3_46_37_PM.png">

Will keep gathering -- and adding additional conclusions from the interviews -- as we get more coming in :)

**Comment by chrislarry33** [comment]
Solid and interesting work Kat

More leads:
Jeremy Berman, leading investigation of "individual" members of Hive: jeremy@shopsocialagency.com Just reach out, he is affable and responsive

Hive Berlin: Michelle Thorne, valentin.muenscher@wikimedia.de and silvia.arlt@wikimedia.de

Hive Denver (very early stages) Jim Stephens: stephens.jim@scienceandtech.org

Hive Manilla (very early) fayetandog@gmail.com

Would be good to do new Hive project manager simona@mozillafoundation.org

Also I know Jess talked to Kari in K.C. but maybe reach out to her to see if she filled out form (or has she, would be good to confirm)

Also could you draft a quick email that has the 1-2-3 of responding to the form and why? We can share widely in NYC, Chicago, Toronto and via Twitter and see if we get some Randos (if you did this already I apologize, just point me to where and I will make sure it goes out Monday)

**Comment by keyboardkat** [comment]
Hey @chrislarry33 - thanks for the positive feedback! Is always fun to put data together so I'm happy to continue doing this as we receive more and the results become more conclusive. Would love to get to a place where we can make a small slidedeck about the process and our findings -- we're getting there!

Regarding the leads, today I got in touch with: 
- Valentin and Silvia from Hive Berlin (again, they didn't answer my first email)
- Hive Denver
- Hive Manilla
- Simona
- Jeremy Berman
- Kari

And @chrislarry33 here's the 3 step process I've been sharing with folks when I ask them to be involved via email: 
- 1) Please fill out the survey (under 10 min length) at http://is.gd/7rKuPo 
- 2) Then, let us know the availability for one of you this week for a further (10-20 min) chat about your reflections.
- 3) Lastly, please send the survey along to 3-4 curated Hive community members of your choice in _____, so we can get some additional perspectives from your region. Thank you!

Would be really great if you could do that second send-out email, as I'm sure it'll have more credence coming from you! :)
