### ISSUE TITLE
Identify exemplar projects 

### ISSUE THREAD

**Issue by iamjessklein** [MozillaHive/ARCHIVEhivelabs#2]
Identify exemplar projects to lead with, like http://hivenyc.org/portfolio/ + local initiatives and pull together available assets. For example:
- wireframes
- blogposts
- prototypes
- google docs
- videos

**Comment by chrislarry33** [comment]
Hive wiki page: https://wiki.mozilla.org/Webmaker/Hive

Hive Cookbook: https://wiki.mozilla.org/Webmaker/HiveCookbook

Hive video that will be on front page of global landing page: https://www.dropbox.com/s/s7m1slo9fv04iyq/Hive%20Nat%20Edit%20Final%20Cut3.mp4

Hive Global landing page wireframe (Studio MOFO) https://redpen.io/jx3e5870445bd0809d

Hive Global Hive Learning Network: Building a Global Community of Teachers and Learners: https://docs.google.com/document/d/11PQYakbm6hbF1PqoQm_k4GjCTQ-Emksyq831sV1ctUM/edit

Hive BHAG draft (please don't edit, but read) https://hive.etherpad.mozilla.org/BHAGdoc? See specifically Goal 2: Hive member orgs generate connected learning and web literacy, tools content, curriculum and practice

**Comment by iamjessklein** [comment]
Met the folks at Beam Center at the Hive NYC Portfolio design workshop- they are keen to collaborate on this with us.

**Comment by chrislarry33** [comment]
This etherpad is collecting, lets regroup when all the teams links are there

https://hive.etherpad.mozilla.org/hiveteam1
