### ISSUE TITLE
Identify and contact lead users from the community

### ISSUE THREAD

**Issue by iamjessklein** [MozillaHive/ARCHIVEhivelabs#3]
Identify and contact lead users from the community to get them to start to think about how they might contribute to Hive Labs and to figure out what tools they might already be using to support their work.

**Comment by chrislarry33** [comment]
This is who is beta testing Hive Community badges:

Marc Lesser - NYC
Emmanuel Pratt – Chicago
Karen Jeffrey – Chicago
Ingrid Dahl – Bay Area
Anna Roberts – PGH
Khalif Ali – PGH, Sprout Fund
Ani Martinez – PGH, Sprout Fund
Dustin Stiver – PGH, Sprout Fund

Should I ping Hive directors?

**Comment by iamjessklein** [comment]
cc/ @keyboardkat  :pager:

**Comment by chrislarry33** [comment]
The etherpad for the all Mozilla Hive Team call (11 AM ET every other wednesday, alternating with full team call) is collecting the best links to get a sense of the projects in each city

https://hive.etherpad.mozilla.org/hiveteam1

Lets then pull from here

**Comment by keyboardkat** [comment]
I'll write a script that we can use to collect data from Hive directors and members in survey form. Will help us draw out key themes.

**Comment by simonaramkisson** [comment]
As per conversation @iamjessklein, this issue has been completed.
