### ISSUE TITLE
Create pitch deck for Hive Labs

### ISSUE THREAD

**Issue by iamjessklein** [MozillaHive/ARCHIVEhivelabs#4]
This deck will serve to Communicate strategy and plans to broader Hive and related communities/stakeholders.

Can pull from vision thinking doc: https://docs.google.com/document/d/1vdeFNcZ1xB0RGYdh2lOWIuU9pEdebGmH3DXBAQo1iN4/edit#

**Comment by keyboardkat** [comment]
Have created first draft for pitch here, will make into an open Google Presentation once I've gotten feedback: https://hive.etherpad.mozilla.org/labs-pitch

Plz add/edit @iamjessklein @toolness @chrislarry33 :)

**Comment by iamjessklein** [comment]
:+1: @keyboardkat , good start! I put my edits in the etherpad. On a high level,  I'd like to propose that we use this deck flow, in order to frame the content:
- Big Idea: (1 slide)
- Why are we the right team? (include visuals) (1 slide)
- The problem/opportunity space (2 -4 slides)
- Our solution/ thesis and why now? (3 -5 slides)
- Traction and Validation (2-4 slides)
- What's the future? (1 - 2 slides)
- What's the ask? (1 slide)

**Comment by keyboardkat** [comment]
Cheers, will make edits today for draft #2.

**Comment by iamjessklein** [comment]
I ported over the pitch deck into a google presentation. [Let's use this to edit](http://bit.ly/1nvwE7Y)

**Comment by toolness** [comment]
Cool, if the final deck isn't too huge, I can turn it into a [DZSlides](http://paulrouget.com/dzslides/)-based Thimble make when we're done.

**Comment by iamjessklein** [comment]
nice! that's awesome @toolness - for now, let's build out the content together and then phase 2 will be project make this look and feel good :+1:

**Comment by iamjessklein** [comment]
I am going to mark this draft as complete and will reopen the ticket when we need to get into stylizing.
