### ISSUE TITLE
Identify which tickets from the Cupcakes Dashboard to prioritize

### ISSUE THREAD

**Issue by iamjessklein** [MozillaHive/ARCHIVEhivelabs#6]
Which tickets from "Cupcakes" should we prioritize in order to hit our goal for the heartbeat?

**Comment by iamjessklein** [comment]
I propose that we take on the follow tickets:
- [Designing and refining the first run experience](https://github.com/darrinhenein/cupcake-dashboard/issues/34) 
- [Changing the title](https://github.com/darrinhenein/cupcake-dashboard/issues/12)
- [Adding Github link](https://github.com/darrinhenein/cupcake-dashboard/issues/13)
- [Design a section for wireframes, mocks etc](https://github.com/darrinhenein/cupcake-dashboard/issues/32)
- [Adding a link to discussion](https://github.com/darrinhenein/cupcake-dashboard/issues/26)
- [Adding a CTA for feedback](https://github.com/darrinhenein/cupcake-dashboard/issues/30)

How does this sound to everyone? cc/ @toolness @keyboardkat  @chrislarry33

**Comment by keyboardkat** [comment]
These look good - a few of them I asked David to file the other day. I think this is a good workflow to determine whether Cupcake can work for our needs.

**Comment by iamjessklein** [comment]
I am going to close this ticket for the moment, as we are going to focus on user needs first before hacking on the tool. Will reopen if we circle back to cupcake.
