### ISSUE TITLE
Interview Hivers about their prototyping process

### ISSUE THREAD

**Issue by iamjessklein** [MozillaHive/ARCHIVEhivelabs#7]
Interview Hive members to gain an understanding as to their process for prototyping and what points int the process they are bumping.

**Comment by keyboardkat** [comment]
Will interview Karen re: Hive Toronto and Helen re: Hive Vancouver this week.

**Comment by iamjessklein** [comment]
:+1:  today @toolness and I are meeting with:
- Lainie DeCoursey
- Julia Vallera
- Dixie Ching
- Rafi Santos

I would also like to concretely reach out to members of the Hives (vs. Hive HQ) at somepoint in the next week.

**Comment by keyboardkat** [comment]
Note that this is new process for interviewing Hivers about the interface: 

For each participant:
1) Ask to fill out Google Form at http://is.gd/7rKuPo 
2) Set up meeting time to discuss their reflections, leave specific notes at http://is.gd/cIQfdq
3) Ask participant to send Google Form to 3-4 curated Hive members

All at https://hive.etherpad.mozilla.org/labs-userstories-interviews

**Comment by iamjessklein** [comment]
Moving this to the Captain's Log milestone as it will be a bit ongoing.

**Comment by keyboardkat** [comment]
15 responses and counting now to the survey. Hoping to get 4-5 more to start making some useful visualisations on the results.

**Comment by keyboardkat** [comment]
Have now gotten in touch with Hive Berlin, and Hive Indonesia is sending to their community this week.
