### ISSUE TITLE
Create user stories 

### ISSUE THREAD

**Issue by iamjessklein** [MozillaHive/ARCHIVEhivelabs#8]
## Goal: let's write some user stories for Hive Labers

Focus : first time user who wants to prototype something in conjunction with the Hive community.

First time user assumptions:
- they have a certain level of familiarity with the Hive
- they have no (or little?) code or design background; they aren't experienced in these areas
- they want to make apps,tools or resources for fun [or?] profit [or?] teach web/lit using a template
- they want to know what the Hive Labs story (or value proposition--why would they care to use it?)

**Comment by iamjessklein** [comment]
Let's draft the stories here: https://hive.etherpad.mozilla.org/labs-userstories

**Comment by keyboardkat** [comment]
Have added two user stories, both taken from the use-cases of real community members -- first is Gurvinder, an educator with Hive India, and second is Jing-Wei, a Mozilla Rep in Vancouver.

**Comment by chrislarry33** [comment]
Really like these, added one and some comments.

**Comment by iamjessklein** [comment]
Marking the draft complete. We can go from here and iterate as needed.
