### ISSUE TITLE
Create user research script for Hive interviews

### ISSUE THREAD

**Issue by keyboardkat** [MozillaHive/ARCHIVEhivelabs#9]
Create user research script to gather data from Hivers via interviews and an online survey regarding needs and ideas for the Hive Labs interface.

**Comment by keyboardkat** [comment]
User survey script has been created. Will get initial feedback tomorrow, and then port into a Google form so we can start gathering data. 

https://hive.etherpad.mozilla.org/labs-usersurvey

**Comment by iamjessklein** [comment]
@keyboardkat :+1:  this is great. I added one question to the etherpad.

**Comment by keyboardkat** [comment]
@iamjessklein @toolness @chrislarry33 Hey guys, Hive Labs user research survey now set up at https://docs.google.com/forms/d/1efktnCUV7qZPV41d_0zy6p8D0OF1VeaEhYs9WYht2jA/viewform

And interview pairings from line 72 here: https://hive.etherpad.mozilla.org/labs-usersurvey

Plz put all responses into the form, so I can draw key themes out of the data. Looking forward to it!

**Comment by chrislarry33** [comment]
I have outreached to the Hive Learning Communities in Bay Area and Chattanooga with the form link and some context, will follow up with Lindsey in Cha to do a conversation once form is done.

**Comment by iamjessklein** [comment]
nice :+1:  @chrislarry33  I also reached out to the remainder of Hive NYC, Hive Chicago, Hive Kansas City and I wrote to those we already interviewed and followed up with the questionnaire.

**Comment by keyboardkat** [comment]
Awesome @chrislarry33 @iamjessklein. I'm reaching out to Pittsburgh today, and have emailed Hive Toronto, India and Vancouver folk.

**Comment by keyboardkat** [comment]
Update: We now have 14 replies to survey.

**Comment by iamjessklein** [comment]
Marking this issue as complete as the script is done.
